services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8081:8080"

  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "8080:8080"
